# Generated by Django 5.1.5 on 2025-01-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at']},
        ),
    ]
