# Generated by Django 5.1.5 on 2025-01-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
